stages:
  train:
    cmd: uv run python -m mlopslabs.dataset model=rf
    deps:
    - conf/
    - data/raw/train.csv
    - mlopslabs/dataset.py
    - mlopslabs/modeling/train.py
    outs:
    - models/model.pkl
